-- Transforma la tabla `usuario` al esquema estándar de Django AbstractUser.
-- Idempotente donde es posible. Ejecutar dentro de una transacción.
BEGIN;

-- 1) Columna password (Django: varchar(128) NOT NULL). Se marca todo como
--    inutilizable ('!'); las contraseñas se (re)establecen luego con set_password.
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS password varchar(128);
UPDATE usuario SET password = '!' WHERE password IS NULL OR password = '';
ALTER TABLE usuario ALTER COLUMN password SET NOT NULL;

-- 2) Flags de permisos del admin nativo
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS is_superuser boolean NOT NULL DEFAULT false;
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS is_staff boolean NOT NULL DEFAULT false;

-- 3) Nombres estándar de AbstractUser
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS first_name varchar(150) NOT NULL DEFAULT '';
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS last_name varchar(150) NOT NULL DEFAULT '';
UPDATE usuario SET first_name = LEFT(COALESCE(nombre, ''), 150),
                   last_name  = LEFT(COALESCE(apellido, ''), 150);

-- 4) date_joined
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS date_joined timestamptz;
UPDATE usuario SET date_joined = COALESCE(created_at, now()) WHERE date_joined IS NULL;
ALTER TABLE usuario ALTER COLUMN date_joined SET DEFAULT now();
ALTER TABLE usuario ALTER COLUMN date_joined SET NOT NULL;

-- 5) is_active NOT NULL DEFAULT true
UPDATE usuario SET is_active = true WHERE is_active IS NULL;
ALTER TABLE usuario ALTER COLUMN is_active SET DEFAULT true;
ALTER TABLE usuario ALTER COLUMN is_active SET NOT NULL;

-- 6) rol: ENUM rol_usuario -> varchar(20); admin_iclae -> admin
ALTER TABLE usuario ALTER COLUMN rol DROP DEFAULT;
ALTER TABLE usuario ALTER COLUMN rol TYPE varchar(20) USING rol::text;
UPDATE usuario SET rol = 'admin' WHERE rol = 'admin_iclae';
ALTER TABLE usuario ALTER COLUMN rol SET DEFAULT 'alumno';

-- 7) Marcar administradores como staff/superuser
UPDATE usuario SET is_staff = true, is_superuser = true WHERE rol = 'admin';

-- 8) Eliminar columna heredada y el tipo enum (solo usuario lo usaba)
ALTER TABLE usuario DROP COLUMN IF EXISTS password_hash;
DROP TYPE IF EXISTS rol_usuario;

-- 9) Tablas M2M de permisos (nombres automáticos de Django: usuario_groups / usuario_user_permissions)
CREATE TABLE IF NOT EXISTS usuario_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id uuid NOT NULL REFERENCES usuario(id) DEFERRABLE INITIALLY DEFERRED,
    group_id integer NOT NULL REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT usuario_groups_uniq UNIQUE (usuario_id, group_id)
);
CREATE INDEX IF NOT EXISTS usuario_groups_usuario_id_idx ON usuario_groups(usuario_id);
CREATE INDEX IF NOT EXISTS usuario_groups_group_id_idx ON usuario_groups(group_id);

CREATE TABLE IF NOT EXISTS usuario_user_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id uuid NOT NULL REFERENCES usuario(id) DEFERRABLE INITIALLY DEFERRED,
    permission_id integer NOT NULL REFERENCES auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT usuario_user_permissions_uniq UNIQUE (usuario_id, permission_id)
);
CREATE INDEX IF NOT EXISTS usuario_user_permissions_usuario_id_idx ON usuario_user_permissions(usuario_id);
CREATE INDEX IF NOT EXISTS usuario_user_permissions_permission_id_idx ON usuario_user_permissions(permission_id);

COMMIT;
