# Generated by Django 6.0.4 on 2026-06-03 18:30

import apps.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('alumno', 'Alumno'), ('tutor_udd', 'Tutor UDD'), ('tutor_empresa', 'Tutor Empresa')], default='alumno', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
            managers=[
                ('objects', apps.models.ManejadorUsuario()),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_logro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alumno_badge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.CharField(blank=True, max_length=10, null=True)),
                ('criterio', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'badge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField()),
                ('texto', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('estado_emp', models.TextField(blank=True, null=True)),
                ('estado_udd', models.TextField(blank=True, null=True)),
                ('fecha_revision_emp', models.DateTimeField(blank=True, null=True)),
                ('fecha_revision_udd', models.DateTimeField(blank=True, null=True)),
                ('feedback_emp', models.TextField(blank=True, null=True)),
                ('feedback_udd', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bitacora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BitacoraEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('tipo_archivo', models.CharField(blank=True, max_length=50, null=True)),
                ('tamaño_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bitacora_evidencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('facultad', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'carrera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompetenciaHito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('peso_pct', models.IntegerField()),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'competencia_hito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigEvaluacionPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_bitacoras_pct', models.IntegerField()),
                ('metodo_calculo_bitacoras', models.TextField(blank=True, null=True)),
                ('umbral_bitacoras_pct', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'config_evaluacion_periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rubro', models.CharField(blank=True, max_length=150, null=True)),
                ('presencia', models.TextField(blank=True, null=True)),
                ('empleados_aprox', models.CharField(blank=True, max_length=50, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('enps_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('contacto_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('contacto_email', models.CharField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionHito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('nota_calculada', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('fecha_evaluacion', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluacion_hito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HitoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('semana', models.IntegerField()),
                ('peso_pct', models.IntegerField()),
                ('evaluador', models.TextField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('doc_rubrica_url', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hito_evaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('leida', models.BooleanField(blank=True, null=True)),
                ('enviada', models.BooleanField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_inicio_iclae', models.DateField(blank=True, null=True)),
                ('fecha_fin_iclae', models.DateField(blank=True, null=True)),
                ('total_semanas', models.IntegerField()),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('tipo_ciclo', models.CharField(blank=True, default='semestral', max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'periodo_academico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.TextField(blank=True, null=True)),
                ('carta_motivacion', models.TextField(blank=True, null=True)),
                ('linkedin_snapshot', models.TextField(blank=True, null=True)),
                ('cv_snapshot', models.TextField(blank=True, null=True)),
                ('youtube_snapshot', models.TextField(blank=True, null=True)),
                ('feedback_rechazo', models.TextField(blank=True, null=True)),
                ('fecha_postulacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'postulacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('modalidad', models.TextField(blank=True, null=True)),
                ('vacantes', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProyectoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.TextField(blank=True, null=True)),
                ('semana_actual', models.IntegerField(blank=True, null=True)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proyecto_periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntajeCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                'db_table': 'puntaje_competencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecordatorioMasivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento', models.CharField(blank=True, max_length=50, null=True)),
                ('mensaje', models.TextField()),
                ('cantidad_envios', models.IntegerField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recordatorio_masivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'sede',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'universidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='alumno', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('generacion', models.IntegerField(blank=True, null=True)),
                ('matricula', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('url_linkedin', models.TextField(blank=True, null=True)),
                ('url_cv', models.TextField(blank=True, null=True)),
                ('url_youtube', models.TextField(blank=True, null=True)),
                ('preferences', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TutorEmpresa',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='tutor_empresa', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('area', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tutor_empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TutorUdd',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='tutor_udd', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('departamento', models.CharField(blank=True, max_length=150, null=True)),
                ('max_alumnos', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tutor_udd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenciaBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apps.models.evidencia_bitacora_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])])),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='apps.bitacora')),
            ],
            options={
                'db_table': 'evidencia_bitacora',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='RecordatorioArchivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordatorio_id', models.IntegerField(unique=True)),
                ('archivado_en', models.DateTimeField(auto_now_add=True)),
                ('archivado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recordatorio_archivado',
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_id', models.IntegerField(blank=True, null=True)),
                ('periodo_nombre', models.CharField(max_length=20)),
                ('eliminado_en', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registro_auditoria',
                'ordering': ['-eliminado_en'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='apps.empresa')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_empresa', to='apps.periodoacademico')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_empresa', to='apps.alumno')),
            ],
            options={
                'db_table': 'evaluacion_empresa',
                'unique_together': {('alumno', 'empresa', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='CalificacionCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('7.0'))])),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='apps.competenciahito')),
                ('evaluado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_competencia', to='apps.alumno')),
            ],
            options={
                'db_table': 'calificacion_competencia',
                'unique_together': {('alumno', 'competencia')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('cambiado', 'Cambiado'), ('desvinculado', 'Desvinculado')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_periodo', to='apps.empresa')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_periodo', to='apps.periodoacademico')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_periodo', to='apps.alumno')),
            ],
            options={
                'db_table': 'asignacion_periodo',
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'activo')), fields=('alumno', 'periodo'), name='uniq_asignacion_activa_por_periodo')],
            },
        ),
        migrations.CreateModel(
            name='ProyectoPeriodoTutorEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.proyectoperiodo')),
                ('tutor_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.tutorempresa')),
            ],
            options={
                'db_table': 'proyecto_periodo_tutor_empresa',
                'unique_together': {('proyecto_periodo', 'tutor_empresa')},
            },
        ),
        migrations.CreateModel(
            name='ProyectoPeriodoTutorUdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.proyectoperiodo')),
                ('tutor_udd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.tutorudd')),
            ],
            options={
                'db_table': 'proyecto_periodo_tutor_udd',
                'unique_together': {('proyecto_periodo', 'tutor_udd')},
            },
        ),
    ]
