# Generated by Django 6.0.4 on 2026-05-23 00:26

import apps.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apps.models.evidencia_bitacora_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])])),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='apps.bitacora')),
            ],
            options={
                'db_table': 'evidencia_bitacora',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
