# Generated by Django 6.0.4 on 2026-05-23 21:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_evidenciabitacora'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('7.0'))])),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_competencia', to='apps.alumno')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='apps.competenciahito')),
                ('evaluado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calificacion_competencia',
                'unique_together': {('alumno', 'competencia')},
            },
        ),
    ]
