# Generated by Django 6.0.4 on 2026-05-23 23:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_calificacioncompetencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_empresa', to='apps.alumno')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='apps.empresa')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_empresa', to='apps.periodoacademico')),
            ],
            options={
                'db_table': 'evaluacion_empresa',
                'unique_together': {('alumno', 'empresa', 'periodo')},
            },
        ),
    ]
