# Generated by Django 6.0.4 on 2026-05-23 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_evaluacionempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordatorioArchivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordatorio_id', models.IntegerField(unique=True)),
                ('archivado_en', models.DateTimeField(auto_now_add=True)),
                ('archivado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recordatorio_archivado',
            },
        ),
    ]
