# Generated by Django 6.0.4 on 2026-05-31 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_recordatorioarchivado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoPeriodoTutorEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.proyectoperiodo')),
                ('tutor_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.tutorempresa')),
            ],
            options={
                'db_table': 'proyecto_periodo_tutor_empresa',
                'unique_together': {('proyecto_periodo', 'tutor_empresa')},
            },
        ),
        migrations.CreateModel(
            name='ProyectoPeriodoTutorUdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.proyectoperiodo')),
                ('tutor_udd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.tutorudd')),
            ],
            options={
                'db_table': 'proyecto_periodo_tutor_udd',
                'unique_together': {('proyecto_periodo', 'tutor_udd')},
            },
        ),
    ]
