# Generated by Django 6.0.4 on 2026-06-01 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_migrar_tutores_existentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_id', models.IntegerField(blank=True, null=True)),
                ('periodo_nombre', models.CharField(max_length=20)),
                ('eliminado_en', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registro_auditoria',
                'ordering': ['-eliminado_en'],
            },
        ),
    ]
