# Generated by Django 6.0.4 on 2026-06-02 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_poblar_carreras_semilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('cambiado', 'Cambiado'), ('desvinculado', 'Desvinculado')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_periodo', to='apps.alumno')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_periodo', to='apps.empresa')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_periodo', to='apps.periodoacademico')),
            ],
            options={
                'db_table': 'asignacion_periodo',
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'activo')), fields=('alumno', 'periodo'), name='uniq_asignacion_activa_por_periodo')],
            },
        ),
    ]
